### ISSUE TITLE
Follow upstream versioning and use "released versions"

### ISSUE THREAD

**Issue by tbroyer** [nathanhammond/libphonenumber#14]
It'd be great if your "packaging" followed the upstream versioning, and if it were built from "released versions" (i.e. tags in upstream repository).
For now, unless I missed the info somewhere, one can't really tell which upstream commit your 0.9.3 "release" is based on.

We're using libphonenumber on the server side in Java and I was just asked to review a change that brought it to the client side, through webjars.org, and was surprised to read the version as 0.9.0 while we're using libphonenumber 7.0.10 in Java.

**Comment by nathanhammond** [comment]
It's a 0.x because this isn't 1:1 compatible with libphonenumber and because there is no way to distinguish my adding/changing a feature which breaks backwards compatibility or upstream doing the same. I'll add something in the README which identifies which version it is based off of, but I'm not going to track upstream version numbers since both values are valuable pieces of information.

Closing, but look for a new release tonight based on 7.2.4.

**Comment by tbroyer** [comment]
Thanks, that makes sense.

(and thanks for the new release)
