### ISSUE TITLE
Play well with CommonJS

### ISSUE THREAD

**Issue by ptarjan** [nathanhammond/libphonenumber#2]
Can you make your library work with nodejs as well please? Basically check if `module.exports` exists, and if so attach all your methods to that instead of the global `phoneUtils`.

**Comment by nathanhammond** [comment]
I'm not exactly sure how this would end up working because the point at which I handle the "exporting" is at compile time, not runtime. It seems like I would have to compile multiple versions of this in order for it to play nicely with CommonJS.

I was intending to test this, but right now the HEAD versions of the dependent repos (as recommended by the build instructions) do not produce a working build (googlei18n/libphonenumber#630).

Once things build again I'll be doing nothing more than this in order to test that it works:
```js
goog.exportSymbol('phoneUtils.isPossibleNumber', isPossibleNumber);
goog.exportSymbol('phoneUtils.isPossibleNumberWithReason', isPossibleNumberWithReason);
// ...
```

```js
goog.exportSymbol('module.exports.isPossibleNumber', isPossibleNumber);
goog.exportSymbol('module.exports.isPossibleNumberWithReason', isPossibleNumberWithReason);
// ...
```

Let me know if you can get it to build, and, if so, see what the result is! I'll be watching for notes on the other issue before I come back here to try again.

**Comment by nathanhammond** [comment]
(I did update the build script in order to account for Google's ongoing migration to GitHub, so make sure you pull prior to testing!)

**Comment by ptarjan** [comment]
Thanks for looking into it. 

I also tried to build it before and do something similar to your exportSymbol change and couldn't get it to compile. My error message was different though. 

```
[exec] libphonenumber/vendor/libphonenumber/javascript/i18n/phonenumbers/phonemetadata.pb.js:2044: ERROR - Property set$Metadata never defined on goog.proto2.Message
     [exec] goog.proto2.Message.set$Metadata(i18n.phonenumbers.NumberFormat, {
```

**Comment by ptarjan** [comment]
Lots of people are looking for an npm version of libphonenumber and I think yours could fit the bill if you did this.

Some people are even willing to pay: https://www.freelancer.com/jobs/Javascript/Port-Google-libPhoneNumber-browserify/

**Comment by ptarjan** [comment]
There is a module on npm, so you don't need to support CommonJS. https://www.npmjs.com/package/libphonenumber

Your module is most useful when running under browserify, as the npm module does dynamic filename `readFileSync` which browserify can't use. Sadly the first line your file assumes `this` is defined as `window` which in browserify it does not. I'll open another bug about that.
