### ISSUE TITLE
Trouble building the project - help please

### ISSUE THREAD

**Issue by ShenglinGuo** [nathanhammond/libphonenumber#21]
Hi, First I like to thank you for the excellent library. This is much easier to use than the original google library. I have some new phone number formatting issue where the new version of the phone lib will resolve. I am getting error says file not found on line 105 of the build xml (prepare-country-metadata) and getting 127 code from Ant. I know this is most likely that my Ant or Ant contrib is not setup properly, but I never used Ant before and could not figure out where it went wrong. 

I have installed ANT and Ant-contrib using homebrew on mac
brew install ant (1.9.2)
brew install ant-contrib (1.00b3)

I tried to include ant-contrib inside the project using following 
http://stackoverflow.com/questions/12891893/how-to-include-ant-contrib-jar-dynamically-in-ant

<taskdef resource="net/sf/antcontrib/antlib.xml">
     <classpath>
         <fileset dir="${basedir}/ant.lib/ant-contrib"/>
     </classpath>
</taskdef>

It will be great if I can build the latest myself, if not would you mind build and publish the latest version again.

Thank you

**Comment by nathanhammond** [comment]
It currently doesn't build for me either and I don't have time to figure out why as I'm unfamiliar with ant or the Java ecosystem. I'm closing this issue not because I don't want to help, but because I'm unable to. If you'd like to spend the time tracing through it I'll be glad to update this per a PR from you if you can get it to build!
