### ISSUE TITLE
build.sh: 10: build.sh: Syntax error: "(" unexpected

### ISSUE THREAD

**Issue by askucher** [nathanhammond/libphonenumber#9]
Run
```
sh build.sh 
```
Got
```
build.sh: 10: build.sh: Syntax error: "(" unexpected
```

**Comment by nathanhammond** [comment]
This isn't enough information to figure out what your issue is. I need platform, whether `sh` is actually `bash`, versions, and more. I don't intend to change the array behavior of the build script since compatibility for the build step isn't a primary goal of mine and the repo includes a built version.

I'm closing this as "won't fix," but if you wish to open a PR which moves the `git` handling into `ant`'s `build.xml` process I would accept that. :)
